// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 1/6/2026, 4:21:06 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/kamontools/PMSPlayground/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamontools/PMSPlayground/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamontools/PMSPlayground/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamontools/PMSPlayground/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamontools/PMSPlayground/app/plugins/**/*.{js,ts,mjs}","/Users/kamontools/PMSPlayground/app/composables/**/*.{js,ts,mjs}","/Users/kamontools/PMSPlayground/app/utils/**/*.{js,ts,mjs}","/Users/kamontools/PMSPlayground/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/kamontools/PMSPlayground/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/kamontools/PMSPlayground/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/kamontools/PMSPlayground/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;